#!/usr/bin/python

import json

import configparser
import netifaces

from tv_guide_updater.auth import Auth
from tv_guide_updater.channel_list import ChannelList


def get_config():
    config = configparser.ConfigParser()
    config.read('etc/tv-guild-updater.conf')
    iptv_interface = config['device']['iptv_interface']
    iptv_ip = netifaces.ifaddresses(iptv_interface)[netifaces.AF_INET][0]['addr']
    print('iptv_ip: ' + iptv_ip)
    config['device']['iptv_ip'] = iptv_ip
    return config


def main():
    auth = Auth(get_config())
    auth.authenticate()
    channel_list = ChannelList(auth.session, auth.base_url, auth.get_channel_list_data)
    channels = channel_list.get_channels()
    print(json.dumps(channels, ensure_ascii=False, indent=4))


if __name__ == '__main__':
    main()
